version: '3.8'

services:

  database:
    image: mariadb
    container_name: container_db
    restart: on-failure
    environment:
      - MARIADB_USER=$USER_DB
      - MARIADB_PASSWORD=$PWD_DB
      - MARIADB_DATABASE=WoodMaster
      - MARIADB_ROOT_PASSWORD=$PWD_DB
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql/data
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          memory: 512M
volumes:
  database: