name: Deploy on staging

on:
  workflow_dispatch:
    inputs:
      deploy:
        required: true
        type: boolean
jobs:
  # # Efetua o deploy no servidor
  deploy-on-server:
    runs-on: ubuntu-latest
    environment: staging
    if: inputs.deploy
    steps:
      -
        name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: print out example job
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME_SSH }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.KEY_PASS}}
          port: ${{ secrets.PORT }}
          script: |
            export TAG=${{ env.BRANCH_NAME }} && \
            cd api_wood_master && \
            docker stop api_woodMaster && docker rm api_woodMaster && \
            docker images | grep k4im/api_wood_master | awk '{print $3}' | xargs docker rmi -f && \
            docker-compose up -d
    
  
