name: Tests

on:
  workflow_dispatch:
    inputs:
      run-tests:
        required: true
        type: boolean  

jobs:
  unit-tests:
    environment: staging
    runs-on: ubuntu-latest
    if: inputs.run-tests
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      - run: npm i
        working-directory: backend/
      - run: npm test
        working-directory: backend/